Repository toggl/track-extension, pull requests merged in 2018-12, with the labels that each got.

#1215 Fix various bugsnag issues
  src/scripts/background.js
  src/scripts/common.js
  src/scripts/lib/bugsnag.js
Labels: high-priority

#1158 Prevent keydown event bubbling when inside toggl popup
  src/scripts/common.js
Labels: bug

#1120 Add produck integration
  README.md
  package-lock.json
  src/scripts/content/produck.js
  src/scripts/origins.js
  src/styles/style.css
Labels: integration-request
