Repository toggl/track-extension, pull requests merged in 2019-01, with the labels that each got.

#961 Add support turtle.ai
  README.md
  package-lock.json
  src/scripts/content/turtle.js
  src/scripts/origins.js
  src/scripts/origins.json
  src/styles/style.css
Labels: integration-request

#1260 Fix continued entries not copying tags
  src/scripts/background.js
Labels: wip

#1240 Fix tag input behaviour when using keyboard
  src/scripts/lib/autocomplete.js
Labels: awaiting-deploy
